
["Fishing Dangers Config"]
	#Chance of each entity in Dangers list, match with Dangers list order 
	#First number will be the spawn chance of the first entity in danger list 
	#Total chance should be between 0 and 1. 
	#Example: [0.5,0.3,0.15,0.05]
	"Chance List" = [1.0]
	#Danger spawn chance, default:0.1
	"Danger spawn chance" = 1.0
	#Dangers list. Example: ["minecraft:tnt","minecraft:drowned","minecraft:fireball"]
	"Dangers List" = ["minecraft:player"]

